version: '3'
services:
  web:
    image: python:3.7
    environment:
        - PYTHONUNBUFFERED=1
    working_dir: /usr/src/studioghiblimovielist
    command: sh web-start.sh
    volumes:
      - ${PWD}:/usr/src/studioghiblimovielist
    ports:
      - 8000:8000
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./config/redis.conf:/redis.conf
    command: [ "redis-server", "/redis.conf" ]
