version: '3'
services:
  web:
    image: python:3.7
    environment:
        - PYTHONUNBUFFERED=1
        - REDIS_CACHE=redis://redis:6379/1
    working_dir: /usr/src/studioghiblimovielist
    command: sh web-start.sh
    volumes:
      - ${PWD}:/usr/src/studioghiblimovielist
    depends_on:
      - redis
    networks:
      - nginx_network
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./config/redis.conf:/redis.conf
    command: [ "redis-server", "/redis.conf" ]
    networks:  # <-- here
      - nginx_network
  nginx:
    image: nginx:1.13
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - web
    networks:  # <-- here
      - nginx_network
networks:  # <-- and here
  nginx_network:
    driver: bridge